blank_issues_enabled: false
contact_links:
  - name: Something else / a question
    url: https://github.com/LunaBelleElite/LunaPanel/discussions
    about: Not quite a bug or a feature idea? Start a discussion instead.
